# Generated by Django 5.2.3 on 2025-06-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'باز'), ('In Review', 'در حال بررسی'), ('Awaiting Customer Response', 'در انتظار پاسخ مشتری'), ('Closed', 'بسته شده')], default='Open', max_length=80, verbose_name='وضعیت تیکت'),
        ),
    ]
