# Generated by Django 5.2.3 on 2025-06-13 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین فعالیت'),
        ),
    ]
